### ISSUE TITLE
merging into the appc repo

### ISSUE THREAD

**Issue by philips** [mcuadros/rocketizer#1]
Hello @mcuadros 

Thanks for putting this together? Would you be willing to help out the app container project by providing this code as a library? It would solve this issue: https://github.com/appc/spec/issues/15

The only details to sort out would be:
- Changing the license to apache 2.0 for consistency with the rest of the repo
- Making it a library instead of a standalone tool

It would be cool if the rocketizer tool just used the library from appc. Then we can keep the library up to date as the spec changes.

Thanks,

Brandon

**Comment by mcuadros** [comment]
Hi @philips 

Sure I don't have any problem on do that, just tell me how proceed. Even better I can merge the code into the main repository instead of keep it as external dependency.

And use if as from the appc/spec library in the tool.

This code is working for the old ACI spec, needs a refactor to get working with the new spec.

Too the `FROM` expression from docker is ignored and then just a few cases of the Dockerfiles are working.

**Comment by jonboulle** [comment]
@mcuadros Awesome, we would love to get it merged. Basically that would just involve you putting it under Apache 2.0 and submitting a PR against appc/spec - let us know if you need any help.

**Comment by mcuadros** [comment]
Can I make the PR as is (changing the license) and then work on the appc/spec repository making more PRs?
